# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
